function [fitresult, gof] = getSigmoidModel(X, label)
%CREATEFIT(X,label)
%  Create a fit.
%
%  Data for 'sigmoidModel' fit:
%      X Input : X -> ground reaction force along z-axis
%      Y Output: label -> contact label
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Jan-2022 10:22:02


%% Fit: 'sigmoidModel'.
[xData, yData] = prepareCurveData( X, label );

% Set up fittype and options.
ft = fittype( '1./(1+exp(a*x+b))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.304495428364679 0.547389996705107];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );



